# Generated by Django 5.1.5 on 2025-03-21 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_purchase_virtual_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_name', models.CharField(max_length=255)),
                ('delivery_price', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='delivery_shipping_id',
        ),
        migrations.AddField(
            model_name='purchase',
            name='delivery_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.shipping'),
        ),
    ]
