# Generated by Django 5.1.5 on 2025-03-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_shipping_remove_purchase_delivery_shipping_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Prepared By Seller', 'Prepared By Seller'), ('On Delivery', 'On Delivery'), ('Canceled', 'Canceled'), ('Success', 'Success')], max_length=20),
        ),
    ]
