# Generated by Django 5.1.5 on 2025-03-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_purchase_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='city',
        ),
    ]
