# Generated by Django 5.1.5 on 2025-03-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_mission_missionprogress_mission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Green Tech & Gadget', 'Green Tech & Gadget'), ('Sustainable Living', 'Sustainable Living'), ('Eco-Friendly Home', 'Eco-Friendly Home'), ('Eco-Friendly Fashion', 'Eco-Friendly Fashion')], max_length=50),
        ),
    ]
