# Generated by Django 5.1.5 on 2025-04-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_address_phone_number_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Prepared By Seller', 'Prepared By Seller'), ('On Delivery', 'On Delivery'), ('Canceled', 'Canceled'), ('Success', 'Success')], max_length=20),
        ),
    ]
