# Generated by Django 5.1.5 on 2025-04-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_purchase_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
