# Generated by Django 5.0.7 on 2025-04-07 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_purchase_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WasteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='waste_images/')),
                ('waste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.wastetype')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('waste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_methods', to='api.wastetype')),
            ],
        ),
        migrations.CreateModel(
            name='Myth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('waste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myths', to='api.wastetype')),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('waste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='api.wastetype')),
            ],
        ),
    ]
