# Generated by Django 5.0.7 on 2025-04-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_wastetype_wasteimage_processingmethod_myth_fact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myth',
            name='waste',
        ),
        migrations.RemoveField(
            model_name='processingmethod',
            name='waste',
        ),
        migrations.RemoveField(
            model_name='wasteimage',
            name='waste',
        ),
        migrations.DeleteModel(
            name='Fact',
        ),
        migrations.DeleteModel(
            name='Myth',
        ),
        migrations.DeleteModel(
            name='ProcessingMethod',
        ),
        migrations.DeleteModel(
            name='WasteImage',
        ),
        migrations.DeleteModel(
            name='WasteType',
        ),
    ]
