# Generated by Django 5.1.5 on 2025-04-09 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_wastetype_wasteimage_processingmethod_myth_fact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='proof_payment',
        ),
    ]
