# Generated by Django 5.1.5 on 2025-04-12 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_reelvideos_video_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCollection',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('waste_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('waste_type', models.CharField(choices=[('organic', 'Organic'), ('non_organic', 'Non Organic'), ('hazardous', 'Hazardous'), ('paper', 'Paper'), ('residual', 'Residual')], max_length=20)),
                ('waste_condition', models.CharField(choices=[('clean', 'Clean'), ('dirty', 'Dirty'), ('mixed', 'Mixed')], max_length=20)),
                ('processing_facility', models.CharField(choices=[('recycling_plant', 'Recycling Plant'), ('biogas_facility', 'Biogas Facility'), ('landfill', 'Landfill'), ('other', 'Other')], max_length=20)),
                ('usage_before_disposal', models.CharField(choices=[('single_use', 'Single Use'), ('reused', 'Reused'), ('repurposed', 'Repurposed')], max_length=20)),
                ('scanned_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
