# Generated by Django 5.1.5 on 2025-04-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_wastecollection_admin_wastecollection_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastecollection',
            name='scanned_data',
        ),
    ]
