# Generated by Django 5.1.5 on 2025-04-12 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_wastecollection_scanned_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastecollection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
