# Generated by Django 5.1.5 on 2025-04-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_wastecollection_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_watched_video',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
