# Generated by Django 5.1.5 on 2025-04-15 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermissiondatadays',
            options={'verbose_name_plural': 'User  Mission Data (Daily)'},
        ),
        migrations.AlterModelOptions(
            name='usermissiondataweeks',
            options={'verbose_name_plural': 'User  Mission Data (Weekly)'},
        ),
    ]
