# Generated by Django 5.1.5 on 2025-04-15 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_usermissiondatadays_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(choices=[('Thank You For The Donation', 'Thank You For The Donation'), ('Payment Failed', 'Payment Failed'), ('You Have Successfully Ordered a Product', 'You Have Successfully Ordered a Product'), ('You Have Successfully Withdrawn Your Money', 'You Have Successfully Withdrawn Your Money')], max_length=255)),
                ('type', models.CharField(choices=[('Donation', 'Donation'), ('Payment Failed', 'Payment Failed'), ('Success Ordered A Product', 'Success Ordered A Product'), ('Successful Withdrawing', 'Successful Withdrawing')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
