# Generated by Django 5.1.5 on 2025-04-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('waste_type', models.CharField(choices=[('organic', 'Organic'), ('non_organic', 'Non Organic'), ('hazardous', 'Hazardous'), ('paper', 'Paper'), ('residual', 'Residual')], max_length=20)),
                ('waste_condition', models.CharField(choices=[('clean', 'Clean'), ('dirty', 'Dirty'), ('mixed', 'Mixed')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='wastecollection',
            name='waste_condition',
        ),
        migrations.RemoveField(
            model_name='wastecollection',
            name='waste_type',
        ),
        migrations.RemoveField(
            model_name='wastecollection',
            name='waste_weight',
        ),
        migrations.AddField(
            model_name='wastecollection',
            name='wastes',
            field=models.ManyToManyField(related_name='waste_collections', to='api.waste'),
        ),
    ]
