# Generated by Django 5.1.5 on 2025-04-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_waste_remove_wastecollection_waste_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='rank',
            field=models.IntegerField(unique=True),
        ),
    ]
