# Generated by Django 5.1.5 on 2025-04-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_voucher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='category',
            field=models.CharField(choices=[('entertainment', 'Entertainment'), ('F&B', 'Food & Beverage'), ('Shopping', 'Shopping'), ('Travel', 'Travel')], max_length=20),
        ),
    ]
