# Generated by Django 5.1.5 on 2025-04-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_voucher_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(choices=[('Thank You For The Donation', 'Thank You For The Donation'), ('Payment Failed', 'Payment Failed'), ('Order Failed', 'Order Failed'), ('You Have Successfully Ordered a Product', 'You Have Successfully Ordered a Product'), ('You Have Successfully Withdrawn Your Money', 'You Have Successfully Withdrawn Your Money'), ('You Have Redeemed A Voucher', 'You Have Redeemed A Voucher')], max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Donation', 'Donation'), ('Payment Failed', 'Payment Failed'), ('Order Failed', 'Order Failed'), ('Success Ordered A Product', 'Success Ordered A Product'), ('Successful Withdrawing', 'Successful Withdrawing'), ('Redeemed A Voucher', 'Redeemed A Voucher')], max_length=50),
        ),
    ]
