# Generated by Django 5.1.5 on 2025-04-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_notification_message_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherredeem',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
