# Generated by Django 5.1.5 on 2025-04-17 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_points_is_addition_points_is_subtract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='expires_at',
        ),
        migrations.CreateModel(
            name='PointsExpire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired_points', models.IntegerField()),
                ('expired_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_expire_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
