# Generated by Django 5.1.5 on 2025-04-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='breathable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='compostable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nontoxic',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
