# Generated by Django 5.1.5 on 2025-03-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='virtual_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
