# Generated by Django 5.1.5 on 2025-03-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=3),
        ),
    ]
