# Generated by Django 5.1.5 on 2025-03-22 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_donation_id_alter_missionlist_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionlist',
            name='mission_target_description',
        ),
    ]
