# Generated by Django 5.1.5 on 2025-03-22 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_missionlist_mission_target_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missionprogress',
            old_name='mission',
            new_name='mission_id',
        ),
    ]
