# Generated by Django 5.0.7 on 2025-04-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_user_total_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Prepared By Seller', 'Prepared By Seller'), ('On Delivery', 'On Delivery'), ('Canceled', 'Canceled'), ('Success', 'Success')], default='Pending', max_length=20),
        ),
    ]
