# Generated by Django 5.1.5 on 2025-04-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_donation_proof_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
