# Generated by Django 5.1.5 on 2025-04-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_donation_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bank_issuer',
            field=models.CharField(blank=True, choices=[('BCA', 'BCA'), ('Mandiri', 'Mandiri'), ('BRI', 'BRI')], max_length=10, null=True),
        ),
    ]
