# Generated by Django 5.1.5 on 2025-04-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_user_bank_issuer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reelvideos',
            name='video_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
