# Generated by Django 5.1.5 on 2025-04-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_wastecollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastecollection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
