# Generated by Django 5.1.5 on 2025-04-12 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_wastecollection_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastecollection',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wastecollection',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastecollection',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wastecollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
