# Generated by Django 5.1.5 on 2025-04-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_wastecollection_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastecollection',
            name='wastes',
            field=models.ManyToManyField(blank=True, related_name='waste_collections', to='api.waste'),
        ),
    ]
