# Generated by Django 5.1.5 on 2025-04-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_wastecollection_wastes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermissiondatadays',
            name='total_donation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermissiondataweeks',
            name='total_donation_count',
            field=models.IntegerField(default=0),
        ),
    ]
