# Generated by Django 5.1.5 on 2025-04-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_usermissiondatadays_total_donation_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionprogress',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
