# Generated by Django 5.1.5 on 2025-04-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_voucher_voucherredeem'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='voucher/'),
        ),
    ]
