# web: gunicorn backend.wsgi --log-file - 
#or works good with external database
# web: python manage.py migrate && gunicorn backend.wsgi
web: python manage.py migrate && gunicorn backend.wsgi:application --log-level=info
worker: celery -A backend worker --loglevel=info
beat: celery -A backend beat --loglevel=info